version: '3'

services:
  hs-inventory:
    build: .
    restart: unless-stopped
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=hs_inventory
      - DB_PASSWORD=hs_inventory
      - DB_NAME=hs_inventory
      # IMPORTANT: Change this to something unique and random
      - JWT_SECRET=
      - INVENTORY_DEMO_MODE=true
      - FENIX_BASE_URL=https://fenix.tecnico.ulisboa.pt/
      - FENIX_CLIENT_ID=
      - FENIX_CLIENT_SECRET=
      - FENIX_REDIRECT_URL=

  mysql:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_USER=hs_inventory
      - MYSQL_PASSWORD=hs_inventory
      - MYSQL_DATABASE=hs_inventory
      - MYSQL_RANDOM_ROOT_PASSWORD=true
